### ISSUE TITLE
Structure présentation

### ISSUE THREAD

**Issue by bryelandt** [LBRAI2219/working-with-models-team-vin-chaud#11]
Antoine tu préfères quoi comme structure (Guillaume ton avis compte aussi si tu veux le donner):

- On présente d'abord le but du modèle (genre qu'il simule l'architecture, les échanges avec le sol, qu'il est composé de mini modèles, etc) puis le fonctionnement (point de vue code).
- Ou l'inverse (d'abord la structure du code puis le but)

Je travaille sur des slides pour bien expliquer la structure de code en ce moment ;)

**Comment by bryelandt** [comment]
# Trop de texte?
autre possibilité: on fait 7 boites avec les 7 dossiers (et pas 6 ^^) et on enlève la partie de droite mais il faut l'expliquer à l'oral d'office
![image](https://user-images.githubusercontent.com/32547143/33804547-a20860f4-dda7-11e7-9c6f-4db65955b49d.png)

**Comment by arummens** [comment]
Je propose de commencer avec le but histoire que tout le monde suive et ensuite enchaîner avec une présentation du code, ton image me parait être un bon point de départ ;)

**Comment by arummens** [comment]
Il ne faut pas oublier les commentaire de Xavier à propose du fonctionnement du nitrate dans le sol !
