### ISSUE TITLE
Guillaume

### ISSUE THREAD

**Issue by arummens** [LBRAI2219/working-with-models-team-vin-chaud#12]
Tu saurais mettre sur github le code r que tu avais écrit il y a deux semaines stp Guillaume ? 

Merci ! !

**Comment by guillaumelobet** [comment]
je l'avais directmeent dessus ici: https://github.com/LBRAI2219/working-with-models-team-vin-chaud/tree/master/outputs

**Comment by arummens** [comment]
Merci !!
