### ISSUE TITLE
est-ce bien?

### ISSUE THREAD

**Issue by bryelandt** [LBRAI2219/working-with-models-team-vin-chaud#5]
Dear M. Postma,

We are currently working on your OpenSimRoot model under the guidance of Xavier Draye and Guillaume Lobet for our courses at the UCL.

Our knowledge of the C++ language and the complexity of the model make it very difficult to understand and use it.

Is it possible to meet you or one of your colleagues to talk about it?
We can come to Juelich any day of the week (before the 10th of November if possible).

Sincerely yours,

Antoine Rummens
Brieuc Ryelandt

**Comment by guillaumelobet** [comment]
Très bien. Je changerai juste ça:

> Our limited knowledge of the C++ language and the complexity of the model make it difficult for us to understand and use it.
