### ISSUE TITLE
Postma  ne répond pas

### ISSUE THREAD

**Issue by bryelandt** [LBRAI2219/working-with-models-team-vin-chaud#6]
Que faire?

**Comment by guillaumelobet** [comment]
Vous pouvez essayer de lui renvoyer le même mail. Il est sans doute passé inaperçu dans sa boite mail.

**Comment by guillaumelobet** [comment]
On vient de recevoir mail de Jouke, Et il semble que sont mail de réponse ne passe pas. Je vois dans son mail que l'adresse qui a été utilisée est `bryelandt@oasis.uclouvain.be` . Est-ce que vous savez essayer, soit avec l'adresse `@student.uclouvain.be`, soit avec une autre (genre google?)

**Comment by bryelandt** [comment]
Oui j'ai renvoyé le mail hier avec mon adresse UCLouvain j'avais mal paramétré thunderbird en changeant l'adresse du serveur.
Merci !

**Comment by guillaumelobet** [comment]
OK, parce qu'il viens de nous envoyer un mail (il y a une heure) disant qu'il avait reçu deux fois le mail et répondu deux fois. Donc il semble que celui d'hier ne soit pas passé non plus...

**Comment by bryelandt** [comment]
Mince... 
Normalement il l'a reçu 2 fois + celle d'hier où j'ai forwardé en ajoutant que j'avais un soucis de config dans mes mails (après l'avoir réglé évidemment) et que du coup il pouvait l'envoyer à mon adresse uclouvain.

En fait bryelandt@oasis.uclouvain.be c'est l'adresse serveur et brieuc.ryelandt@student.uclouvain.be c'est l'adresse mail donc là où il doit envoyer la réponse et j'avais indiqué l'autre dans thunderbird du coup depuis le changement de serveur personne ne savait me répondre (heureusement que j'envoie pas beaucoup de mail :p )

**Comment by guillaumelobet** [comment]
Johanness sera sur Skype cet après midi (Jeudi) à 16h15.

**Comment by guillaumelobet** [comment]
Son id Skype est postma.werk
