### ISSUE TITLE
Github

### ISSUE THREAD

**Issue by arummens** [LBRAI2219/working-with-models-team-vin-chaud#8]
Je n'arrive pas à accéder aux dossier mis sur github depuis paraview
Impossible de faire tourner nitrate 0.2 par exemple
Clonage du repository rate à chaque tentative ...
Il est mis que le clonage réussit mais qu'il y a un problème au niveau du check-out 
![clonage github](https://user-images.githubusercontent.com/32547062/33386905-56a53eee-d52c-11e7-8bf0-99f90178a261.png)

**Comment by guillaumelobet** [comment]
d'après l'erreur, il semble qu'il n'arrive pas a cloner le dossier "outputs/nitrate\*2". Le probleme est p-e l' "\*" dans le nom. Essayez de le changer puis de re-cloner

**Comment by arummens** [comment]
En remplaçant, l'* tout fonctionne !
